server:
  port: 19082

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dnliu.pdms.dao

spring:
  datasource:
    url: jdbc:mysql://${db.url}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 10000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      useGlobalDataSourceStat: true

logging:
  config: classpath:logback-spring.xml

#微信配置
weixing:
  appid: wxf6b9e85f20aec010
  secret: 5f11b701a2450094ded6f9c75a07e34d
  code2SessionUrl: https://api.weixin.qq.com/sns/jscode2session

