[mysql]
DBName=lfhdb
IP=10.211.55.3
Port=3306
Charset=utf8
UserName=root
UserPass=mysql
UserPass=BPoGBvHJ2sY=
#[mysql]
#DBName=lfhdb
#IP=119.29.103.193
#Port=3306
#Charset=utf8
#UserName=lfhmysql
#UserPass=mw1UBLnhmdL6F7Shtkpv4Q==
[email]
EmailUser=956423698@qq.com
EmailPassword=OBRSFhxBPKs+Q6fepAjkIQ==
EmailHost=smtp.qq.com:587
[backup]
path=/Users/dnliu/GoStudy/pdms/bin
ip=119.29.103.193
dbname=clPUNLGnBMA=
dbuser=dVymeBiIF0PY6Ig5o9+K3w==
dbpassword=mw1UBLnhmdL6F7Shtkpv4Q==
