package com.dnliu.pdms.entity;

import java.util.Date;

public class LoginLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.login_time
     *
     * @mbggenerated
     */
    private String loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.ip_address_parse
     *
     * @mbggenerated
     */
    private String ipAddressParse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.id
     *
     * @return the value of tb_login_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.id
     *
     * @param id the value for tb_login_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.user_id
     *
     * @return the value of tb_login_log.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.user_id
     *
     * @param userId the value for tb_login_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.user_name
     *
     * @return the value of tb_login_log.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.user_name
     *
     * @param userName the value for tb_login_log.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.login_time
     *
     * @return the value of tb_login_log.login_time
     *
     * @mbggenerated
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.login_time
     *
     * @param loginTime the value for tb_login_log.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.ip_address
     *
     * @return the value of tb_login_log.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.ip_address
     *
     * @param ipAddress the value for tb_login_log.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.ip_address_parse
     *
     * @return the value of tb_login_log.ip_address_parse
     *
     * @mbggenerated
     */
    public String getIpAddressParse() {
        return ipAddressParse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.ip_address_parse
     *
     * @param ipAddressParse the value for tb_login_log.ip_address_parse
     *
     * @mbggenerated
     */
    public void setIpAddressParse(String ipAddressParse) {
        this.ipAddressParse = ipAddressParse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.remark
     *
     * @return the value of tb_login_log.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.remark
     *
     * @param remark the value for tb_login_log.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.create_time
     *
     * @return the value of tb_login_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.create_time
     *
     * @param createTime the value for tb_login_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.update_time
     *
     * @return the value of tb_login_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.update_time
     *
     * @param updateTime the value for tb_login_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}