##数据库建表语句
create table TB_USER(
    USER_ID  CHAR(32) NOT NULL,
    USER_NAME  VARCHAR(64),
    USER_PASSWORD VARCHAR(32),
    USER_EMAIL  VARCHAR(64),
    USER_PHONE  VARCHAR(20),
    REGISTERED_TIME  CHAR(14),
    REMARKS  VARCHAR(512),
    PASSWORD_LAST_CHANGE_DAY  CHAR(8),
    DATA_STATUS  VARCHAR(2),
    DATA_ADD_DATE  CHAR(8),
    DATA_ADD_TIME  CHAR(14),
    DATA_MOD_DATE  CHAR(8),
    DATA_MOD_TIME  CHAR(14),
	VERIF_CODE  VARCHAR(10),
    RSV1  VARCHAR(180),
    RSV2  VARCHAR(180),
    RSV3  VARCHAR(180),
    RSV4  VARCHAR(180),
    RSV5  VARCHAR(180),
    PRIMARY KEY(USER_ID)
);

create table TB_LOGIN_LOG(
    DATA_ID CHAR(32) NOT NULL,
    DATA_DATE  CHAR(8),
    USER_ID  CHAR(32),
    OPER  VARCHAR(2),
    OPER_IP VARCHAR(20),
    OPER_DATE  CHAR(8),
    OPER_TIME  CHAR(14),
    REMARK  VARCHAR(512),
    RSV1  VARCHAR(180),
    RSV2  VARCHAR(180),
    RSV3  VARCHAR(180),
    RSV4  VARCHAR(180),
    RSV5  VARCHAR(180),
    PRIMARY KEY(DATA_ID)
);


create table TB_SYSPARAMS(
    DATA_ID  CHAR(32) NOT NULL,
    DATA_DATE  CHAR(8),
    PARA_NAME  VARCHAR(64),
    PARA_VALUE  VARCHAR(512),
    RSV1  VARCHAR(180),
    RSV2  VARCHAR(180),
    RSV3  VARCHAR(180),
    RSV4  VARCHAR(180),
    RSV5  VARCHAR(180),
    PRIMARY KEY(DATA_ID)
);


create table TB_DICT(
    DATA_ID  CHAR(32) NOT NULL,
    DATA_DATE  CHAR(8),
    GOUP_ID  VARCHAR(10),
    GOUP_NAME  VARCHAR(64),
    DICT_KEY  VARCHAR(64),
    DICT_VALUE  VARCHAR(90),
    RSV1  VARCHAR(180),
    RSV2  VARCHAR(180),
    RSV3  VARCHAR(180),
    RSV4  VARCHAR(180),
    RSV5  VARCHAR(180),
    PRIMARY KEY(DATA_ID)
);

create table TB_CONTENT(
    DATA_ID  CHAR(32) NOT NULL,
    DATA_DATE  CHAR(8),
    USER_ID  CHAR(32),
    DATA_TYPE  VARCHAR(4),
    TITLE  VARCHAR(120),
    CONTENT1  TEXT(65532),
    CONTENT2  TEXT(65532),
    CONTENT3  TEXT(65532),
    CONTENT4  TEXT(65532),
    CONTENT5  TEXT(65532),
    STATUS VARCHAR(2),
    ADD_DATE  CHAR(8),
    ADD_TIME  CHAR(14),
    MOD_DATE  CHAR(8),
    MOD_TIME  CHAR(14),
    RSV1  VARCHAR(180),
    RSV2  VARCHAR(180),
    RSV3  VARCHAR(180),
    RSV4  VARCHAR(180),
    RSV5  VARCHAR(180),
    PRIMARY KEY(DATA_ID)
);


create table TB_CONTACT(
    DATA_ID  CHAR(32) NOT NULL,
    DATA_DATE  CHAR(8),
    USER_ID  CHAR(32),
    DATA_TYPE  VARCHAR(4),
    TITLE  VARCHAR(120),
    CONTACT TEXT(65532),
    RSV1  VARCHAR(180),
    RSV2  VARCHAR(180),
    RSV3  VARCHAR(180),
    RSV4  VARCHAR(180),
    RSV5  VARCHAR(180),
    PRIMARY KEY(DATA_ID)
);




